# Generated by Django 3.0 on 2020-04-27 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=20)),
                ('desc', models.CharField(max_length=300)),
                ('photo', models.ImageField(blank=True, default='', null=True, upload_to='images/')),
            ],
        ),
    ]
