# Generated by Django 3.0 on 2020-04-27 22:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Productcat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prodcat', models.CharField(max_length=100)),
                ('prod_cat_desc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Productsitems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=20)),
                ('desc', models.CharField(max_length=300)),
                ('prize', models.FloatField()),
                ('photo', models.ImageField(blank=True, default='', null=True, upload_to='images/')),
                ('sale', models.BooleanField(default=False)),
                ('top_sale', models.BooleanField(default=False)),
                ('prodcat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Productcat')),
            ],
        ),
    ]
