# Generated by Django 3.0 on 2020-04-29 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20200428_0402'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcat',
            name='photo',
            field=models.ImageField(blank=True, default='', null=True, upload_to='images/'),
        ),
    ]
