# Generated by Django 3.0 on 2020-04-29 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_productcat_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='A',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mcat', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='B',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scat', models.CharField(max_length=100)),
                ('mcat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.A')),
            ],
        ),
        migrations.CreateModel(
            name='C',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sscat', models.CharField(max_length=100)),
                ('mcat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.A')),
                ('scat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.B')),
            ],
        ),
        migrations.CreateModel(
            name='D',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=100)),
                ('mcat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.A')),
                ('scat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.B')),
                ('sscat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.C')),
            ],
        ),
    ]
