# Generated by Django 2.2 on 2020-05-06 04:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_a_b_c_d'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_user', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('prod_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Productsitems')),
            ],
        ),
    ]
