# Generated by Django 2.2 on 2020-05-06 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='b',
            name='mcat',
        ),
        migrations.RemoveField(
            model_name='c',
            name='mcat',
        ),
        migrations.RemoveField(
            model_name='c',
            name='scat',
        ),
        migrations.RemoveField(
            model_name='d',
            name='mcat',
        ),
        migrations.RemoveField(
            model_name='d',
            name='scat',
        ),
        migrations.RemoveField(
            model_name='d',
            name='sscat',
        ),
        migrations.DeleteModel(
            name='A',
        ),
        migrations.DeleteModel(
            name='B',
        ),
        migrations.DeleteModel(
            name='C',
        ),
        migrations.DeleteModel(
            name='D',
        ),
    ]
